roommeet-1/roommeet/urls.py
from django.conf.urls import *
from django.contrib import admin

admin.autodiscover()


#regex to view function mapping
urlpatterns = patterns('roommeet.views',
    url(r'^$', 'meet'),
	url(r'^get_marks/$', 'get_marks'),
    url(r'^meet/$', 'meet'),
    url(r'^meet_person/$', 'meet_person'),
    url(r'^meet_house/$', 'meet_house'),
    url(r'^remove_person/$', 'remove_person'),
    url(r'^remove_house/$', 'remove_house'),
    url(r'^remove_managed_house', 'remove_managed_house'),
    url(r'^add_house/$', 'add_house'),
	url(r'^edit_house/$', 'edit_house'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^product_page/', 'product_page'),
    
)

#CAS
urlpatterns += patterns('',
    url(r'^accounts/login/$', 'django_cas.views.login'),
    url(r'^accounts/logout/$', 'django_cas.views.logout'),
    #url(r'^facebook/', include('django_facebook.urls')),
    #url(r'^fbaccounts/', include('django_facebook.auth_urls')),
)

roommeet-1/roommeet/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets
from people.models import Person
from houses.models import House

from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'}, format='%m/%d/%Y')

class ProfileForm(forms.Form):
	first_name = forms.CharField(max_length=50)
	last_name = forms.CharField(max_length=50)
	gchoices = (('',''),('Male','Male'),('Female','Female'),('Decline','Decline to State'),)
	gender = forms.ChoiceField(choices=gchoices)
	year = forms.RegexField(regex=r'201[4-8]', label='Class Year')
	company = forms.CharField(max_length=100)
	start = forms.DateField(widget=DateInput(), input_formats=('%m/%d/%Y',))
	end = forms.DateField(widget=DateInput(),  input_formats=('%m/%d/%Y',))
	dchoices = (('',''),('Roommate','Roommate'), ('Friends','Friends'),)
	desired = forms.ChoiceField(choices=dchoices)
	lat_s = forms.DecimalField(max_digits=13, decimal_places=10, widget=forms.HiddenInput)
	lon_s = forms.DecimalField(max_digits=13, decimal_places=10, widget=forms.HiddenInput)

class HouseForm(forms.Form):

	name = forms.CharField(max_length=50, label='Contact Name')
	lat_h = forms.DecimalField(max_digits=13, decimal_places=10, widget=forms.HiddenInput)
	lon_h = forms.DecimalField(max_digits=13, decimal_places=10, widget=forms.HiddenInput)
	hstart = forms.DateField(widget=DateInput(), input_formats=('%m/%d/%Y',), label='Start')
	hend = forms.DateField(widget=DateInput(),  input_formats=('%m/%d/%Y',), label='End')
	contact_email = forms.EmailField(max_length=50)
	description = forms.CharField(max_length=1000, widget=forms.Textarea)	
	hid = forms.DecimalField(widget=forms.HiddenInput, required=False)

roommeet-1/roommeet/templates/addhouse.html

<style> 
#id_name, #id_hstart, #id_hend, #id_description { 
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 200px; 
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0; 
  }   

  #id_description { 
	height: 200px;
}
  
  form input[type=email]{ 
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 200px;
    resize: none; 
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0; 
  }


</style>



<ul class="nav nav-list" style="color:#c2c2c2">
  <li  style="font-weight:bold;">&nbsp;&nbsp;&nbsp;&nbsp;Please click on the map where <br>&nbsp;&nbsp;&nbsp;&nbsp;you will be offering housing</li>
  <br>


  {% if form.errors %}
  <p style="color: red;">
    <b>&nbsp;&nbsp;&nbsp;&nbsp;Please correct the error{{ form.errors|pluralize }} below.</b>
  </p>
  {% endif %}

  {{ form.non_field_errors }}

  <form id="hform" action="/add_house/" method="post">
    {% csrf_token %}

    <table border="1" style="width:300px">
      <table>
        {% for field in form.visible_fields %}
        <div class="fieldWrapper">
          {% if field.errors %}     
          <tr><td>{{ field.errors }}</td></tr>
          {% endif %}
          <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;{{ field.label_tag }}</td><td> &nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td style="color: black;"> {{ field }}<br></td>
          </tr>
        </div>

        {% endfor %}
      </table>
      {% for hidden in form.hidden_fields %}
      {% if hidden.errors %}
      <br>
      <p style="color: red;">
        Please click on the map.
      </p>
      <br>
      {% endif %}
      {{ hidden }}
      {% endfor %}

      <input type="submit" class="btn btn-primary" style="margin: 2%;  width:120px;" value="Add House">
      <a id="close_addHouse" class="btn btn-danger" style="margin: 2%; width:110px;">Cancel</a>
    </form>

  </ul>

roommeet-1/roommeet/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>{% block titlebar %} RoomMeet {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    
	<!-- Favicon -->
	<link rel="shortcut icon" href="../static/favicon.ico" type="image/x-icon"/>
	
    <!-- Custom styles for this template -->


    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
	a, td {
		cursor: pointer
	}
 

    html, body, #map-canvas {
      height: 100%;
      margin: 0px;
      padding: 0px;
      padding-top: 25px;
    }
    #map-canvas {
      position:fixed;
      left:0px;
      right:0px;
      top:50px;
    }

    .btn-outlined {
    border-radius: 0;
        -webkit-transition: all 0.3s;
           -moz-transition: all 0.3s;
                transition: all 0.3s;
    }
    .btn-outlined.btn-primary {
        background: none;
        border: 3px solid #428bca;
        color: #428bca;
    }
    .btn-outlined.btn-primary:hover,
    .btn-outlined.btn-primary:active {
        color: #FFF;
        background: #428bca;
        border-color: #428bca:
    }

    .btn-outlined.btn-success {
        background: none;
        border: 3px solid #5cb85c;
        color: #5cb85c;
    }
    .btn-outlined.btn-success:hover,
    .btn-outlined.btn-success:active {
        color: #FFF;
        background: #47a447;
    }

    .btn-outlined.btn-info {
        background: none;
        border: 3px solid #5bc0de;
        color: #5bc0de;
    }
    .btn-outlined.btn-info:hover,
    .btn-outlined.btn-info:active {
        color: #FFF;
        background: #39b3d7;
    }

    .btn-outlined.btn-warning {
        background: none;
        border: 3px solid #f0ad4e;
        color: #f0ad4e;
    }
    .btn-outlined.btn-warning:hover,
    .btn-outlined.btn-warning:active {
        color: #FFF;
        background: #ed9c28;
    }

    .btn-outlined.btn-danger {
        background: none;
        border: 3px solid #d9534f;
        color: #d9534f;
    }
    .btn-outlined.btn-danger:hover,
    .btn-outlined.btn-danger:active {
        color: #FFF;
        background: #d2322d;
    }
    .controls {
      margin-top: 16px;
      border: 1px solid transparent;
      border-radius: 2px 0 0 2px;
      box-sizing: border-box;
      -moz-box-sizing: border-box;
      height: 32px;
      outline: none;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
    }

    #pac-input {
      background-color: #fff;
      padding: 0 11px 0 13px;
      width: 400px;
      font-family: Roboto;
      font-size: 15px;
      font-weight: 300;
      text-overflow: ellipsis;
    }

    #pac-input:focus {
      border-color: #4d90fe;
      margin-left: -1px;
      padding-left: 14px;  /* Regular padding-left + 1. */
      width: 401px;
    }

    .pac-container {
      font-family: Roboto;
    }

    #type-selector {
      color: #fff;
      background-color: #4d90fe;
      padding: 5px 11px 0px 11px;
    }

    #type-selector label {
      font-family: Roboto;
      font-size: 13px;
      font-weight: 300;
    }
  }
  </style>
  {% block headext %}
  {% endblock %}
  </head>

  <body>
    {% block precontainter %}
    {% endblock %}
    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" id="topnavbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">{% block navtitle %} <span style="color:#83ACFD;opacity=.99;">Room</span><span style="color:#FF4D4D;opacity=.99;">Meet</span>{% endblock %}</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% block lnavitems %} 
            {# active is initial, href = url, >title</a = title #}
            <li class="active"><a href="/meet/">Meet</a></li>
            <li><a href="/talk/">Talk</a></li>
            <li><a href="/house/">House</a></li>
            {% endblock %}

          </ul>
          <ul class="nav navbar-nav navbar-right">
                {% block rnavdropdown %}

                <li id="profile_nav"><a id="profile_toggle">Profile</a></li>

                <li><a href="/accounts/logout/">Logout</a></li>
                {% endblock %}

              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </div>
    <div class="container-fluid">
      <!-- Main component for a primary marketing message or call to action -->
      {% block mainpage %}

      {% endblock %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="{{STATIC_URL}}/js/bootstrap.min.js"></script>



    {% block scriptext %}
    {% endblock %}

  </body>
</html>

roommeet-1/roommeet/templates/buttonfill.html
<b>Name:</b>  {{ person.first_name }} {{ person.last_name }}
<br>
<b>Company:</b> {{ person.company }}
<br>
<b>Year:</b> {{ person.year }}
<br>
<b>Desired:</b> {{ person.desired }}
<br>
<div align='right'>

{% if not isSelf %}
    {% if add %}
        <button type='submit' id='person_add' onclick='meetPerson("{{ person.netid }}")'  class='btn btn-outlined btn-xs btn-block active btn-success'> Add </button>
    {% else %}
        <button type='submit' id='person_remove' onclick='removePerson("{{ person.netid }}")' class='btn btn-outlined btn-xs btn-block active btn-danger'> Remove </button>
	{% endif %}
{% endif %}

roommeet-1/roommeet/templates/edithouse.html
<style> 
#id_name, #id_hstart, #id_hend, #id_description { 
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 200px; 
    resize: none;
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0; 
  }   

  #id_description { 
	height: 200px;
}
  
  form input[type=email]{ 
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 200px; 
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0; 
  }



</style>



<ul class="nav nav-list" style="color:#c2c2c2">
  <li  style="font-weight:bold;">&nbsp;&nbsp;&nbsp;&nbsp;Please click on the map where <br>&nbsp;&nbsp;&nbsp;&nbsp;you will be offering housing</li>
  <br>


  {% if form.errors %}
  <p style="color: red;">
    <b>&nbsp;&nbsp;&nbsp;&nbsp;Please correct the error{{ form.errors|pluralize }} below.</b>
  </p>
  {% endif %}

  {{ form.non_field_errors }}

  <form id="heform" action="/edit_house/" method="post">
    {% csrf_token %}

    <table border="1" style="width:300px">
      <table>
        {% for field in form.visible_fields %}
        <div class="fieldWrapper">
          {% if field.errors %}     
          <tr><td>{{ field.errors }}</td></tr>
          {% endif %}
          <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;{{ field.label_tag }}</td><td> &nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td style="color: black;"> {{ field }}<br></td>
          </tr>
        </div>

        {% endfor %}
      </table>
      {% for hidden in form.hidden_fields %}
      {% if hidden.errors %}
      <br>
      <p style="color: red;">
        Please click on the map.
      </p>
      <br>
      {% endif %}
      {{ hidden }}
      {% endfor %}

      <input type="submit" class="btn btn-primary" style="margin: 2%;  width:120px;" value="Save Changes">
      <a id="close_editHouse" class="btn btn-danger" style="margin: 2%; width:110px;">Cancel</a>
    </form>

  </ul>

roommeet-1/roommeet/templates/housefill.html
<b>Start:</b>  {{ house.start }}
<br>
<b>End:</b> {{ house.end }}
<br>
<b>Contact:</b> {{ house.name }}
<br>
<div align='right'>


    {% if add %}
        <button type='submit' id='house_add' onclick='meetHouse("{{ house.id }}")'  class='btn btn-outlined btn-xs btn-block active btn-success'> Add </button>
    {% else %}
        <button type='submit' id='house_remove' onclick='removeHouse("{{ house.id }}")' class='btn btn-outlined btn-xs btn-block active btn-danger'> Remove </button>
	{% endif %}

roommeet-1/roommeet/templates/housetablefill.html
{% for person in friend_list %}
<tr >
    <td>
        <p>{{ person.first_name }}  {{ person.last_name }}</p> 
    </td>
    <td>
        <p>{{ person.year }}</p>      
    </td>
    <td>
        <p>{{ person.start.month }}/{{person.start.day}}/{{person.start.year}} - {{ person.end.month }}/{{person.end.day}}/{{person.end.year}}</p>
    </td>
    <td>
        <p id="talk_dist"> not too far</p>  
    </td>
    </tr>
    <tr  class="c" >
    <td colspan="3" style="border-bottom: initial;"><p>
        Company: {{ person.company }} <br>
        Contact: 
        <a href="mailto:{{ person.netid }}@princeton.edu?Subject=RoomMeet%20Hello"> {{ person.netid }}@princeton.edu </a>
        <br>
        Desired: {{ person.desired }}</p>
        </td>
        <td style="border-bottom: initial;"><p><br>
        <button type="submit" style:"right:10px; z-index:4;" class="btn btn-sm btn-danger" id="{{ person.netid }}-remove" onclick="removeList('{{ person.netid }}')"> remove </button> </p>
    </td>
</tr>
{% endfor %}

roommeet-1/roommeet/templates/managehousetablefill.html
{% for house in house_list %}
<tr >
    <td>
        <p>{{ house.name }}</p> 
    </td>
    <td>
        <p>{{ house.start.month }}/{{house.start.day}}/{{house.start.year}} - {{ house.end.month }}/{{house.end.day}}/{{house.end.year}}</p>
    </td>
</tr>
    <tr  class="c"  atr="atr">
    <td style="border-bottom: initial; text-align:left; word-wrap:break-word;"><p>
    Contact: 
        <a href="mailto:{{ house.contact_email }}?Subject=RoomMeet%20Hello"> {{ house.contact_email }} </a>
        <br>
        Description: <br><textarea readonly style="height:50px;width:250px;background:transparent;resize:none;border:none;">{{ house.description }}</textarea>

        </p>
        </td>
        <td style="border-bottom: initial;">
        <p>
        <br>
        <button type="submit" class="btn btn-sm btn-danger" id="{{ house.id }}-remove" onclick="removeHouseList('{{ house.id }}')"> remove </button>
		<button type="submit" class="btn btn-sm btn-success" id="{{ house.id }}-edit" onclick="showEditHouse('{{ house.id }}')"> edit </button> </p>
		</td>
</tr>
{% endfor %}

roommeet-1/roommeet/templates/myhousetablefill.html
{% for house in my_houses %}
<tr >
    <td>
        <p>{{ house.name }}</p> 
    </td>
    <td>
        <p>{{ house.start.month }}/{{house.start.day}}/{{house.start.year}} - {{ house.end.month }}/{{house.end.day}}/{{house.end.year}}</p>
    </td>
    <td>
        <p id="house_dist_{{ forloop.counter }}"><script language="JavaScript" type="text/javascript">
            var rad = function(x) {
                return x * Math.PI / 180;
            };
            
            var calculateDistance = function(p1lat, p1lon, p2lat, p2lon) {
                var theta = p1lon-p2lon
                var dist = Math.sin(rad(p1lat)) * Math.sin(rad(p2lat)) + Math.cos(rad(p1lat)) * Math.cos(rad(p2lat)) * Math.cos(rad(theta));
                dist = Math.acos(dist)
                dist = dist * 180/Math.PI
                dist = dist * 60 * 1.1515
                return dist
            };

            var round = function(num) {
                var rounded = Math.round(num * 10)/10;
                return rounded;
            }
            $("#house_dist_{{ forloop.counter }}").append(round(calculateDistance({{me.lat}},{{me.lon}},{{house.lat}},{{house.lon}})));

            
            </script></p>
    </td>
    </tr>
    <tr  class="c" atr="atr">
    <td colspan="2" style="border-bottom: initial; text-align: left; word-wrap:break-word;"><p>
        Contact: 
        <a href="mailto:{{ house.contact_email }}?Subject=RoomMeet%20Hello"> {{ house.contact_email }} </a>
        <br>
         Description: <br><textarea readonly style="height:50px;width:250px;background:transparent;resize:none;border:none;">{{ house.description }}</textarea></p>
        </td>
        <td style="border-bottom: initial;"><p><br>
        <button type="submit" style:"right:10px; z-index:4;" class="btn btn-sm btn-danger" id="{{ house.id }}-remove" onclick="removeHouse('{{ house.id }}')"> remove </button> </p>
    </td>
</tr>
{% endfor %}

roommeet-1/roommeet/templates/profile.html
<style> 
  form input[type=text]{ 
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 150px; 
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0; 
  } 
  #id_desired{
    display: inline-block;
      -webkit-appearance: none;        /*Removes default chrome and safari style*/
      -moz-appearance: none;          /* Removes Default Firefox style*/


      
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 150px; 
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0;

      /*My custom style for fonts*/

      color: #000000;
    }

#id_gender{
    display: inline-block;
      -webkit-appearance: none;        /*Removes default chrome and safari style*/
      -moz-appearance: none;          /* Removes Default Firefox style*/


      
    padding: 1px 20px; 
    border: 0; 
    height:25px; 
    width: 150px; 
    border-radius: 10px; 
    -moz-border-radius: 10px; 
    -webkit-border-radius: 10px; 
    box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -moz-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-box-shadow: 1px 1px 0 0 #FFF, 5px 5px 40px 2px #BBB inset; 
    -webkit-background-clip: padding-box; 
    outline:0;

      /*My custom style for fonts*/

      color: #000000;
    }
  


  form label{
    height: 40px;
    line-height: 45px;
  } 
  td
  {
    max-width: 100px;
    overflow: visible;
    text-overflow: ellipsis;
    white-space: nowrap;
  }


</style>



<ul class="nav nav-list" style="color:#c2c2c2">
  <li  style="font-weight:bold;">&nbsp;&nbsp;&nbsp;&nbsp;Please click on the map where <br>&nbsp;&nbsp;&nbsp;&nbsp;you will be working</li>
  <br>


  {% if form.errors %}
  <p style="color: red;">
    <b>&nbsp;&nbsp;&nbsp;&nbsp;Please correct the error{{ form.errors|pluralize }} below.</b>
  </p>
  {% endif %}

  {{ form.non_field_errors }}

  <form id="pform" action="/meet/" method="post">
    {% csrf_token %}

    <table border="1" style="width:300px">
      <table>
        {% for field in form.visible_fields %}
        <div class="fieldWrapper">
          {% if field.errors %}     
          <tr><td>{{ field.errors }}</td></tr>
          {% endif %}
          <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;{{ field.label_tag }}</td><td> &nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td style="color: black;"> {{ field }}<br></td>
          </tr>
        </div>

        {% endfor %}
      </table>
      {% for hidden in form.hidden_fields %}
      {% if hidden.errors %}
      <br>
      <p style="color: red;">
        Please click on the map.
      </p>
      <br>
      {% endif %}
      {{ hidden }}
      {% endfor %}

      <input type="submit" class="btn btn-primary" style="margin: 2%;  width:120px;" value="Save">
      <a id="close_profile" class="btn btn-danger" style="margin: 2%; width:110px;">Cancel</a>
    </form>

  </ul>

roommeet-1/roommeet/templates/settings.html
{% extends base.html %}

{% block headext %}
<head>
	<title>Basic modal demo</title>
		<style type="text/css">
			body { margin: 0; }
			#shade, #modal { display: none; }
			#shade { position: fixed; z-index: 100; top: 0; left: 0; width: 100%; height: 100%; }
			#modal { position: fixed; z-index: 101; top: 33%; left: 25%; width: 50%; }
			#shade { background: silver; opacity: 0.5; filter: alpha(opacity=50); }
		</style>
</head>
{% endblock %}

{% block mainpage %}
<body>
	<div id="shade"></div>
	<div id="modal">
		<textarea rows="5" cols="25"></textarea>
		<button id="close">Close</button>
	</div>

	<p>
		<button id="start">Start</button>
	</p>
	<script type="text/javascript">
	var modal= document.getElementById('modal');
		var shade= document.getElementById('shade');
		document.getElementById('start').onclick= function() {
			modal.style.display=shade.style.display= 'block';
		};
		document.getElementById('close').onclick= function() {
			modal.style.display=shade.style.display= 'none';
		};

		// This code is a workaround for IE6's lack of support for the
		// position: fixed style.
		//
		if (!('maxHeight' in document.body.style)) {
			function modalsize() {
				var top= document.documentElement.scrollTop;
				var winsize= document.documentElement.offsetHeight;
				var docsize= document.documentElement.scrollHeight;
				shade.style.height= Math.max(winsize, docsize)+'px';
				modal.style.top= top+Math.floor(winsize/3)+'px';
			};
			modal.style.position=shade.style.position= 'absolute';
			window.onscroll=window.onresize= modalsize;
			modalsize();
		}
	</script>

</body>

{% endblock %}